version: "3.8"

services:
  airflow:
    build: .
    container_name: phishpipe-airflow

    env_file:
      - .env

    ports:
      - "8080:8080"

    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
      - ./data:/opt/airflow/data

    environment:
      LOAD_EX: "n"
      EXECUTOR: Sequential
      AIRFLOW__WEBSERVER__SECRET_KEY: dev_only_not_for_production

    command: webserver
